apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: schedulertest-aws
spec:
  schedule: "SCHEDULE" # syntax is a same as in system cron jobs
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: schedulertest-aws
            zone: db
        spec:
          volumes:
          - name: pv-nfs-pv1
            persistentVolumeClaim:
              claimName: pvc-nfs-pv1
          imagePullSecrets:
          - name: IMAGESECRET
          containers:
          - name: schedulertest-aws
            volumeMounts:
            - name: pv-nfs-pv1
              mountPath: /srv/nfs/kubedata
            image: sjain2643/scheduler-backup-aws:IMAGEVERSION
            command: ["/bin/sh","cd /srv/nfs/kubedata","sh script.sh"]
            args:
            - /bin/sh
            - -c
            - date; java -jar app.ja
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 9999
            runAsUser: 1000
            supplementalGroups:
            - 9999
